// Generated by 'unplugin-auto-import'
export {}
declare global {
  const usePlaceholderPerson: typeof import('../composables/usePlaceholderPerson')['default']
  const useSelectFormCourseOptions: typeof import('../composables/useSelectFormCourseOptions')['default']
  const useSelectFormSlotOptions: typeof import('../composables/useSelectFormSlotOptions')['default']
}
