// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    2: typeof import("./../components/ui/Dl copy 2.vue")["default"];
    AppLink: typeof import("./../components/app/Link.vue")["default"];
    AppMessage: typeof import("./../components/app/Message.vue")["default"];
    AppNavbar: typeof import("./../components/app/Navbar.vue")["default"];
    Card: typeof import("./../layouts/Card.vue")["default"];
    CardBase: typeof import("./../components/card/Base.vue")["default"];
    CardCard: typeof import("./../components/card/Card.vue")["default"];
    CardLayout: typeof import("./../layouts/CardLayout.vue")["default"];
    copy: typeof import("./../components/ui/Dl copy.vue")["default"];
    DashboardCardLayout: typeof import("./../layouts/DashboardCardLayout.vue")["default"];
    DashboardLayout: typeof import("./../layouts/DashboardLayout.vue")["default"];
    Default: typeof import("./../layouts/Default.vue")["default"];
    DefaultLayout: typeof import("./../layouts/DefaultLayout.vue")["default"];
    EventCard: typeof import("./../components/event/Card.vue")["default"];
    FormContainer: typeof import("./../components/form/Container.vue")["default"];
    FormDivider: typeof import("./../components/form/Divider.vue")["default"];
    FormRow: typeof import("./../components/form/Row.vue")["default"];
    FormSchema: typeof import("./../components/form/Schema.vue")["default"];
    GirdContainer: typeof import("./../components/gird/Container.vue")["default"];
    LayoutDashboardContent: typeof import("./../components/layout/DashboardContent.vue")["default"];
    UiDateString: typeof import("./../components/ui/DateString.vue")["default"];
    UiDateTimeString: typeof import("./../components/ui/DateTimeString.vue")["default"];
    UiDd: typeof import("./../components/ui/Dd.vue")["default"];
    UiDl: typeof import("./../components/ui/Dl.vue")["default"];
    UiDt: typeof import("./../components/ui/Dt.vue")["default"];
    UiH1: typeof import("./../components/ui/H1.vue")["default"];
    UiH2: typeof import("./../components/ui/H2.vue")["default"];
    UiMessage: typeof import("./../components/ui/Message.vue")["default"];
    UiTimeString: typeof import("./../components/ui/TimeString.vue")["default"];
  }
}
