- name: install packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - certbot
    - python3-certbot-nginx
- name: check if certificate already exists
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ nginx_domain_name }}/fullchain.pem"
  register: nginx_cert
- name: stop nginx before requesting certificate
  become: yes
  ansible.builtin.service:
    name: nginx
    state: stopped
  when: not nginx_cert.stat.exists
- name: create certificate
  become: yes
  ansible.builtin.command: >
    certbot certonly --standalone --non-interactive --agree-tos
    --pre-hook "systemctl stop nginx"
    --post-hook "systemctl start nginx"
    -m {{ letsencrypt_email }}
    -d {{ nginx_domain_name }}
  when: not nginx_cert.stat.exists
- name: create nginx site
  become: yes
  ansible.builtin.template:
    src: "{{ nginx_site_template }}"
    dest: /etc/nginx/sites-available/default
    mode: "0644"
  notify: reload_nginx
- name: enable and restart nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
